### ISSUE TITLE
Bug: Select-All, filter down via search, and then either selecting all again or selecting an option will leave the array still filled with previous options

### ISSUE THREAD

**Issue by sharpk1** [hc-oss/react-multi-select-component#474]
First of all, thank you so much for taking the time, effort, and energy to write such a dynamic component!

I do have this lingering bug I have been trying to work through on my project. 

**The setup**: My MultiSelect component is created in such a way that it will render with all options selected. If all options are selected, all of the options on my schema table will be rendered. If nothing is selected, no options on my schema table will be rendered.

**The Expected Behavior**:  Whenever I search for an option, I thought de-selecting the `Select-All` option would remove everything in the array and then I would be able to select my option that would be filtered down

**The Actual Behavior**: Whenever I search for an option, I select the `Select-All` option to de-select whichever options are shown and select the option I filtered via the search. The array still contains the previous options from the first `Select-All` upon first render. 

Shouldn't the `Select-All` be a true select all and be able to either clear out or fill the array with all or nothing? If you can point me in the right direction as far as configuring or maybe even making a PR for the fix. That would stellar.

Cheers!

I have this video to better demonstrate too: 

https://user-images.githubusercontent.com/32557637/132381902-0447646c-d220-44d4-acde-7a14dc797aa1.mp4

**Comment by harshzalavadiya** [comment]
@sharpk1 thanks for reporting this, actully it was supposed to always filter shown option so if it;s filtered it should always apply to filtered options

because if you want to clear all values you can use cross (x) next to dropdown caret icon

I have made two changes in order to fix this
- "select all" will always work for filterd values if there's filter value
- to make this explicitly clear I have added another key that will be shown for filtered keys

![Peek 2021-09-08 13-40](https://user-images.githubusercontent.com/5774849/132471730-f492c1fc-0b5f-42ed-b339-63b331230ba5.gif)

**Comment by harshzalavadiya** [comment]
released `v4.1.10`
