### ISSUE TITLE
Make style injection configurable

### ISSUE THREAD

**Issue by jemmyw** [hc-oss/react-multi-select-component#495]
I've been trying to make the component work inside a shadowRoot web-component but it injects the styles into the document.head tag.

It'd be nice if style injection could be controlled. For example, emotion has a provider that will configure all emotion based components in the tree: https://emotion.sh/docs/cache-provider

**Comment by harshzalavadiya** [comment]
Sorry, It's been long time and since now `tsup` based on `esbuild` does this automatically so customisation might not be possible

the main reason I kept styles auto inject so it will be easy for anyone to get started. we can revisit this if we have any other simpler way that removes barrior of css import

closing this w/ won't fix
