### ISSUE TITLE
Can't import the named export 'createElement' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by shenzheniapps** [hc-oss/react-multi-select-component#540]
![image](https://user-images.githubusercontent.com/13235552/150771259-7a83a21d-eeda-4b8e-b3e5-038bc4b6796b.png)

**Comment by miteshKCS** [comment]
I am getting the same error.

**Comment by harshzalavadiya** [comment]
@shenzheniapps @miteshKCS can you create a minimal reproduction for the same

**Comment by Aabhash97** [comment]
https://github.com/hc-oss/react-multi-select-component/blob/849e00f084e81e99014d49af666d1f8fd28a00de/package.json#L9

@harshzalavadiya  I think in your last PR you have added this module path  by changing it to a .mjs file
which is probably causing issue.

Can you fix asap , it will be a great help , as it is breaking the applications.
Thanks

**Comment by cravi47** [comment]
Following.

**Comment by harshzalavadiya** [comment]
@Aabhash97 @cravi47 I moved the project from babel to tsup, so this is intentional change is there any way I can get a reproduction from anyone since I tried with newer CRA and next and it worked as expected so having any reproduction might be nice, it can be a git repo as well or an package json

meanwhile you can keep using `@4.1` that should work just as expected

**Comment by Aabhash97** [comment]
@harshzalavadiya  Even in older versions, it is throwing same error, Don't wonder why.

**Comment by harshzalavadiya** [comment]
please try with latest version that should fix issue.

in essense please update your react-scripts to latest that should've resolved this anyway

**Comment by Aabhash97** [comment]
@harshzalavadiya  Thanks Buddy👏🏻 You are a hero !!. Appreciate for fixing the problem so quick .
