### ISSUE TITLE
Long delay when selecting an option in the select

### ISSUE THREAD

**Issue by AndriiRafalskyi** [hc-oss/react-multi-select-component#566]
**Describe the bug**
Long delay when selecting an option in the select. The duration of the delay increases in proportion to the number of elements in the select (React SPA app)

**To Reproduce**
1. Render Select with a huge number of options (about 1500 items)
2. Select any option in the select

**Actual behavior**
Element is selected with a delay. 

**Expected behavior**
Element is selected without lags and delays. 

**Screenshots**
https://www.loom.com/share/6da444e779f543969c861ef3ee27a29f

**Comment by harshzalavadiya** [comment]
@AndriiRafalskyi Thanks for reporting but this might be true for every select component library

Implementing it in this component might be little out of scope for this project since I want to keep it as light as possible

but there are few things you can try

1. My first recommendation to use[ `react-select`](https://react-select.com/async#:~:text=Async%20MultiSelect) since you already want to use it as tag based version w/ async filter since, it should be much performance efficient
2. second one might be using either `react-select` or `react-multi-select-component` w/ something like [react-window](https://www.npmjs.com/package/react-window) which can optimize rendering large lists.
